import Head from 'next/head';
import {BsFillMoonFill} from 'react-icons/bs'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Kunduz Rakhat Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 ' >
 <section className=' min-h-screen'>
 <nav className='py-10  mb-12 flex justify-between'>
 <h1 className='text-2xl'>developedbyed</h1>
<ul className='flex items-center'>

<li><BsFillMoonFill className='cursor-pointer text-2xl'/></li>
  <li className='ms-2'>
    <a href='#' className='bg-cyan-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a>
  </li>
</ul>
 </nav>
 
 </section>
      </main>

         </div>
  )
}
